#[derive(Clone, Copy, PartialEq)]
pub struct ResourceConfig {
    pub slug: &'static str,
    pub label: &'static str,
    pub group: &'static str,
    pub endpoint: &'static str,
    pub description: &'static str,
    pub template: &'static str,
}

pub const GROUP_ORDER: &[&str] = &[
    "Identity",
    "Access",
    "Connections",
    "Automation",
    "Commerce",
    "Edge",
];

pub const RESOURCES: &[ResourceConfig] = &[
    ResourceConfig {
        slug: "organizations",
        label: "Organizations",
        group: "Identity",
        endpoint: "/api/organizations",
        description: "Multi-tenant organizations and tenant-level settings.",
        template: r#"{"owner":"admin","name":"demo","display_name":"Demo Organization"}"#,
    },
    ResourceConfig {
        slug: "applications",
        label: "Applications",
        group: "Identity",
        endpoint: "/api/applications",
        description: "OAuth and SSO client applications.",
        template: r#"{"owner":"admin","name":"portal","display_name":"Portal","organization":"demo"}"#,
    },
    ResourceConfig {
        slug: "users",
        label: "Users",
        group: "Identity",
        endpoint: "/api/users",
        description: "User accounts, profile fields, and credentials.",
        template: r#"{"owner":"admin","name":"alice","display_name":"Alice","password":"ChangeMe123!"}"#,
    },
    ResourceConfig {
        slug: "groups",
        label: "Groups",
        group: "Identity",
        endpoint: "/api/groups",
        description: "Hierarchical groups for membership and policy composition.",
        template: r#"{"owner":"admin","name":"engineering","display_name":"Engineering"}"#,
    },
    ResourceConfig {
        slug: "invitations",
        label: "Invitations",
        group: "Identity",
        endpoint: "/api/invitations",
        description: "Invitation links and codes for controlled sign-up.",
        template: r#"{"owner":"admin","name":"invite_demo","display_name":"Demo Invite","code":"invite-demo"}"#,
    },
    ResourceConfig {
        slug: "roles",
        label: "Roles",
        group: "Access",
        endpoint: "/api/roles",
        description: "Casbin-backed role definitions.",
        template: r#"{"owner":"admin","name":"reader","display_name":"Reader"}"#,
    },
    ResourceConfig {
        slug: "permissions",
        label: "Permissions",
        group: "Access",
        endpoint: "/api/permissions",
        description: "Granular permissions assigned to roles.",
        template: r#"{"owner":"admin","name":"read_profile","display_name":"Read Profile","resource_type":"API","resources":"/api/userinfo","actions":"read"}"#,
    },
    ResourceConfig {
        slug: "tokens",
        label: "Tokens",
        group: "Access",
        endpoint: "/api/tokens",
        description: "Issued tokens, authorization codes, and refresh tokens.",
        template: r#"{"owner":"admin","name":"token_demo","application":"portal","organization":"demo","user":"replace-with-user-id"}"#,
    },
    ResourceConfig {
        slug: "sessions",
        label: "Sessions",
        group: "Access",
        endpoint: "/api/sessions",
        description: "Active signin sessions and duplicate-session checks.",
        template: r#"{"owner":"admin","name":"session_demo","application":"portal","user_id":"replace-with-user-id","session_id":"session-demo"}"#,
    },
    ResourceConfig {
        slug: "models",
        label: "Models",
        group: "Access",
        endpoint: "/api/models",
        description: "Casbin authorization models.",
        template: r#"{"owner":"admin","name":"model_demo","display_name":"Model Demo","model_text":"[request_definition]\nr = sub, obj, act"}"#,
    },
    ResourceConfig {
        slug: "adapters",
        label: "Adapters",
        group: "Access",
        endpoint: "/api/adapters",
        description: "Casbin storage adapters.",
        template: r#"{"owner":"admin","name":"adapter_demo","display_name":"Adapter Demo","adapter_type":"Database"}"#,
    },
    ResourceConfig {
        slug: "enforcers",
        label: "Enforcers",
        group: "Access",
        endpoint: "/api/enforcers",
        description: "Casbin enforcers bound to models and adapters.",
        template: r#"{"owner":"admin","name":"enforcer_demo","display_name":"Enforcer Demo","model":"model_demo","adapter":"adapter_demo"}"#,
    },
    ResourceConfig {
        slug: "rules",
        label: "Rules",
        group: "Edge",
        endpoint: "/api/rules",
        description: "WAF, IP, User-Agent, and compound traffic rules.",
        template: r#"{"owner":"admin","name":"rule_demo","rule_type":"User-Agent","expressions":[{"operator":"contains","value":"curl"}],"action":"Block","status_code":403,"reason":"Blocked by Casdog","is_verbose":false}"#,
    },
    ResourceConfig {
        slug: "sites",
        label: "Sites",
        group: "Edge",
        endpoint: "/api/sites",
        description: "Site routing, alerts, TLS bindings, and attached rules.",
        template: r#"{"owner":"admin","name":"site_demo","display_name":"Site Demo","domain":"demo.casdog.local","ssl_mode":"HTTPS Only","port":443,"rules":[]}"#,
    },
    ResourceConfig {
        slug: "providers",
        label: "Providers",
        group: "Connections",
        endpoint: "/api/providers",
        description: "OAuth, email, SMS, payment, storage, and notification providers.",
        template: r#"{"owner":"admin","name":"github","display_name":"GitHub","category":"OAuth","type":"GitHub"}"#,
    },
    ResourceConfig {
        slug: "certs",
        label: "Certificates",
        group: "Connections",
        endpoint: "/api/certs",
        description: "JWT and SAML certificates used for signing.",
        template: r#"{"owner":"admin","name":"jwt_demo","display_name":"JWT Demo","scope":"JWT","type":"x509","crypto_algorithm":"RS256","bit_size":2048,"expire_in_years":10}"#,
    },
    ResourceConfig {
        slug: "resources",
        label: "Resources",
        group: "Connections",
        endpoint: "/api/resources",
        description: "Uploaded files and external resource metadata.",
        template: r#"{"owner":"admin","name":"resource_demo","user_id":"replace-with-user-id","file_name":"demo.txt","file_type":"text/plain","url":"https://example.com/demo.txt"}"#,
    },
    ResourceConfig {
        slug: "webhooks",
        label: "Webhooks",
        group: "Connections",
        endpoint: "/api/webhooks",
        description: "Outgoing event webhooks for audit and automation.",
        template: r#"{"owner":"admin","name":"webhook_demo","organization":"demo","url":"https://example.com/webhook"}"#,
    },
    ResourceConfig {
        slug: "syncers",
        label: "Syncers",
        group: "Connections",
        endpoint: "/api/syncers",
        description: "Directory and database synchronization jobs.",
        template: r#"{"owner":"admin","name":"syncer_demo","organization":"demo","type":"Database","host":"localhost","port":5432,"user_name":"postgres","password":"postgres"}"#,
    },
    ResourceConfig {
        slug: "records",
        label: "Records",
        group: "Automation",
        endpoint: "/api/records",
        description: "Audit records collected from middleware and handlers.",
        template: r#"{}"#,
    },
    ResourceConfig {
        slug: "forms",
        label: "Forms",
        group: "Automation",
        endpoint: "/api/forms",
        description: "Dynamic forms for signup and tickets.",
        template: r#"{"owner":"admin","name":"form_demo","display_name":"Form Demo","form_items":[{"name":"Email","visible":true,"required":true}]}"#,
    },
    ResourceConfig {
        slug: "tickets",
        label: "Tickets",
        group: "Automation",
        endpoint: "/api/tickets",
        description: "Support tickets and issue workflows.",
        template: r#"{"owner":"admin","name":"ticket_demo","display_name":"Ticket Demo","subject":"Demo issue"}"#,
    },
    ResourceConfig {
        slug: "orders",
        label: "Orders",
        group: "Commerce",
        endpoint: "/api/orders",
        description: "Orders generated from products and pricing plans.",
        template: r#"{"owner":"admin","name":"order_demo","display_name":"Order Demo","product_name":"starter","user":"alice"}"#,
    },
    ResourceConfig {
        slug: "products",
        label: "Products",
        group: "Commerce",
        endpoint: "/api/products",
        description: "Sellable products exposed in the store.",
        template: r#"{"owner":"admin","name":"starter","display_name":"Starter"}"#,
    },
    ResourceConfig {
        slug: "plans",
        label: "Plans",
        group: "Commerce",
        endpoint: "/api/plans",
        description: "Subscription plans attached to products.",
        template: r#"{"owner":"admin","name":"starter_monthly","display_name":"Starter Monthly","product":"starter"}"#,
    },
    ResourceConfig {
        slug: "pricings",
        label: "Pricings",
        group: "Commerce",
        endpoint: "/api/pricings",
        description: "Currency-specific pricing rows.",
        template: r#"{"owner":"admin","name":"starter_usd","display_name":"Starter USD","plan":"starter_monthly","currency":"USD","price":9.99}"#,
    },
    ResourceConfig {
        slug: "subscriptions",
        label: "Subscriptions",
        group: "Commerce",
        endpoint: "/api/subscriptions",
        description: "User subscriptions linked to plans and providers.",
        template: r#"{"owner":"admin","name":"subscription_demo","display_name":"Subscription Demo","plan":"starter_monthly","user":"alice"}"#,
    },
    ResourceConfig {
        slug: "payments",
        label: "Payments",
        group: "Commerce",
        endpoint: "/api/payments",
        description: "Payment intents and provider callbacks.",
        template: r#"{"owner":"admin","name":"payment_demo","display_name":"Payment Demo","organization":"demo","provider":"stripe"}"#,
    },
    ResourceConfig {
        slug: "transactions",
        label: "Transactions",
        group: "Commerce",
        endpoint: "/api/transactions",
        description: "Completed payment transactions.",
        template: r#"{"owner":"admin","name":"transaction_demo","display_name":"Transaction Demo","provider":"stripe","user":"alice"}"#,
    },
];

pub fn resource_config(slug: &str) -> Option<ResourceConfig> {
    RESOURCES.iter().copied().find(|config| config.slug == slug)
}
